[package]
name = "game_of_life"
version = "0.1.0"
authors = ["YuichiroSato <sato.yu1ro@gmail.com>"]
edition = "2018"

[dependencies]
gtk = "0.5.0"
relm = "0.15.0"
relm-attributes ="0.15.0"
relm-derive = "0.15.0"
